apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: btc-trading-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/btc-trading-api
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: production
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: latest
